erDiagram
    User {
        integer UserID PK
        varchar Firstname
        varchar LastName "nullable"
        varchar Email UK "nullable"
        varchar Phone UK "nullable"
        varchar PasswordHash
        varchar City
        enum Role "Customer, Admin"
        enum Status "active, disactive"
        timestamp RegistrationDate
        integer Ceredit
        varchar UserPicUrl "nullable"
    }
    Match {
        integer MatchID PK
        timestamp MatchDataTime
        varchar Title
    }
