erDiagram
    User {
        integer UserID PK
        varchar Firstname
        varchar LastName "nullable"
        varchar Email UK "nullable"
        varchar Phone UK "nullable"
        varchar PasswordHash
        varchar City
        enum Role "Customer, Admin"
        enum Status "active, disactive"
        timestamp RegistrationDate
        integer Ceredit
        varchar UserPicUrl "nullable"
    }
    Match {
        integer MatchID PK
        integer VenueID FK
        timestamp MatchDataTime
        integer OrganizerID FK
        varchar Title
    }
    Venue {
        integer VenueID PK
        varchar Name
        varchar Province
        varchar City
        varchar Address
        integer Capacity
    }
    Organizer {
        integer OrganizerID PK
        varchar Name
        varchar ContactInfo
        varchar CancelationPolicy
    }


    %% Relationships
    Match }o--|| Venue : "held at"
    Match }o--|| Organizer : "organized by"
